import { Injectable, computed, signal } from '@angular/core';

const STORAGE_KEY = 'eeg.voice.muted';

/**
 * The spoken countdown and prompts.
 *
 * The browser's own speech synthesis, not a server-side voice: it is the only option
 * with no dependency, no network and no latency, and the protocol's timings are
 * generated by the backend — this only says the words it is told to say. It is
 * deliberately easy to mute, because a voice in the room changes what the subject is
 * doing, and "silent" is a legitimate way to run a protocol.
 */
@Injectable({ providedIn: 'root' })
export class Speech {
  readonly supported = signal(typeof window !== 'undefined' && 'speechSynthesis' in window);
  readonly muted = signal(this.restore());
  readonly spoken = signal<string | null>(null);
  readonly voiceName = signal<string | null>(null);

  private voice: SpeechSynthesisVoice | null = null;

  constructor() {
    if (!this.supported()) return;
    this.pickVoice();
    // Chrome populates the voice list asynchronously; without this the first utterance
    // can use the default voice or nothing at all.
    window.speechSynthesis.addEventListener('voiceschanged', () => this.pickVoice());
  }

  readonly enabled = computed(() => this.supported() && !this.muted());

  setMuted(muted: boolean): void {
    this.muted.set(muted);
    if (muted) this.cancel();
    try {
      localStorage.setItem(STORAGE_KEY, muted ? '1' : '0');
    } catch {
      // A private-mode browser refuses to store; muting still works for this session.
    }
  }

  toggle(): void {
    this.setMuted(!this.muted());
  }

  /** Say something. `interrupt` cuts off whatever is being said. */
  say(text: string, interrupt = true): void {
    this.spoken.set(text);
    if (!this.enabled() || !text.trim()) return;
    const synth = window.speechSynthesis;
    if (interrupt) synth.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = 1;
    utterance.pitch = 1;
    utterance.volume = 1;
    if (this.voice) utterance.voice = this.voice;
    synth.speak(utterance);
  }

  /** The countdown number. Spoken as a bare number, which reads as a count. */
  count(value: number): void {
    this.say(String(value));
  }

  cancel(): void {
    if (this.supported()) window.speechSynthesis.cancel();
  }

  private pickVoice(): void {
    if (!this.supported()) return;
    const voices = window.speechSynthesis.getVoices();
    if (voices.length === 0) return;
    const english = voices.filter((voice) => voice.lang.toLowerCase().startsWith('en'));
    const preferred =
      english.find((voice) => /google uk english female|google us english/i.test(voice.name)) ??
      english.find((voice) => /natural|online/i.test(voice.name)) ??
      english[0] ??
      voices[0];
    this.voice = preferred;
    this.voiceName.set(preferred?.name ?? null);
  }

  private restore(): boolean {
    try {
      return localStorage.getItem(STORAGE_KEY) === '1';
    } catch {
      return false;
    }
  }
}
