/**
 * The shapes the API and the socket actually exchange.
 *
 * REST types are *derived* from the server's own OpenAPI document (generated by
 * `npm run api:types`), so a field renamed on the server breaks the build here rather
 * than producing `undefined` at runtime.
 *
 * The WebSocket frames are hand-written and live in `./messages.ts`: a WebSocket is not
 * an OpenAPI concept, so there is nothing to generate them from. They are kept next to
 * the code that parses them for exactly that reason.
 */
import type { components } from './schema';

type Schemas = components['schemas'];

export type ChannelDoc = Schemas['ChannelDocModel'];
export type ChannelCatalog = Schemas['CatalogModel'];
export type BandDoc = Schemas['BandDocModel'];
export type Montage = Schemas['MontageModel'];
export type HeadPoint = Schemas['HeadPointModel'];

export type FlowStep = Schemas['FlowStepModel'];
export type FlowSpec = Schemas['FlowSpecModel'];
export type FlowStepInput = Schemas['FlowStepInput'];
export type FlowInput = Schemas['FlowInput'];
export type FlowValidation = Schemas['ValidationModel'];
export type PlanPreview = Schemas['PlanPreviewModel'];
export type PlanPhase = Schemas['PlanPhaseModel'];

export type LibraryEntry = Schemas['LibraryEntryModel'];
export type LibraryListing = Schemas['LibraryModel'];
export type LabelSummary = Schemas['LabelSummaryModel'];
export type Segment = Schemas['SegmentModel'];
export type Preview = Schemas['PreviewModel'];
export type Spectrum = Schemas['SpectrumModel'];

export type Status = Schemas['StatusModel'];
export type DeviceStatus = Schemas['DeviceModel'];
export type DeviceInterface = Schemas['DeviceInterfaceModel'];
export type SourceStats = Schemas['SourceStatsModel'];
export type RecordingState = Schemas['RecordingStateModel'];
export type RecordingSummary = Schemas['RecordingSummaryModel'];

export type SessionState = Schemas['SessionStateModel'];
export type EngineState = Schemas['EngineStateModel'];
export type EnginePhase = Schemas['EnginePhaseModel'];

export type SourceRequest = Schemas['SourceRequest'];
export type QuickRecordRequest = Schemas['QuickRecordRequest'];
export type StartSessionRequest = Schemas['StartSessionRequest'];
export type EndpointMetadata = Schemas['ChannelDocModel'];
